// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvTRL2AvMN18s8Y_mSDs18LUypO1Q5Tb0',
    appId: '1:215439199665:web:8202dd78303e97edb50190',
    messagingSenderId: '215439199665',
    projectId: 'evently-c15',
    authDomain: 'evently-c15.firebaseapp.com',
    storageBucket: 'evently-c15.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8hLHAAvJ_rUBA6iHyqUxGTcLC1l0_H8U',
    appId: '1:215439199665:android:04a0b9661b7109d4b50190',
    messagingSenderId: '215439199665',
    projectId: 'evently-c15',
    storageBucket: 'evently-c15.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0lN-ZlvyApNOaB4_6_0m0V-MLQ3S-1Vo',
    appId: '1:215439199665:ios:2d8bf7c71f40080eb50190',
    messagingSenderId: '215439199665',
    projectId: 'evently-c15',
    storageBucket: 'evently-c15.firebasestorage.app',
    iosClientId: '215439199665-l96vsnj0eqkvdph2rmpab59404aoscbl.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventlyC15',
  );

}